export const CART_ADD_MOVIE = 'CART_ADD_MOVIE'
export const CART_REMOVE_MOVIE = 'CART_REMOVE_MOVIE'
export const CART_RECORD_MOVIE_THEATER = 'CART_RECORD_MOVIE_THEATER'
export const CART_RECORD_PAYMENT_METHOD = 'CART_RECORD_PAYMENT_METHOD'

export const CLEAR_CART_ITEMS = 'CLEAR_CART_ITEMS';
export const CLEAR_THEATER_DETAILS = 'CLEAR_THEATER_DETAILS';
export const CLEAR_PAYMENT_DETAILS = 'CLEAR_PAYMENT_DETAILS';